# Generated by Django 6.0.3 on 2026-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[('alluvial', 'Alluvial'), ('black', 'Black'), ('red', 'Red'), ('laterite', 'Laterite'), ('sandy', 'Sandy'), ('clay', 'Clay'), ('loamy', 'Loamy')], max_length=100)),
                ('water_source', models.CharField(max_length=100)),
                ('water_availability', models.CharField(choices=[('continuous', 'Continuous'), ('seasonal', 'Seasonal'), ('scarce', 'Scarce')], max_length=50)),
                ('crop_duration', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
